-- Cron registration for scheduled-ride-digest.
--
-- Every 15 minutes, and deliberately with NO clock logic in the schedule. The
-- function is content-triggered: it pushes a driver only when scheduled work
-- they can claim has newly appeared, and rate-limits per driver. The cron's job
-- is just to ask often enough that the per-driver ceiling — not the sweep
-- interval — is what decides when anyone hears anything.
--
-- Why not a daily send at a fixed hour (the first cut of this): these companies
-- run 24 hours, so there is no company-wide evening, and any hour picked is
-- wrong for whoever is asleep or driving. See the header of the function.
--
-- 15 minutes costs 96 rows/day in cron.job_run_details — under a tenth of what
-- the 2-minute scheduled-release job already writes, and the nightly
-- cleanup-cron-logs job prunes both.
--
-- Requires migration 20260747 (drivers.digest_watermark_at / digest_last_sent_at
-- and rides.became_open_at) to be applied FIRST — the function selects those
-- columns on every run and will error on all of them otherwise.
--
-- Do NOT run this file as-is — the service-role JWT is project-specific and
-- must be copied from an existing cron job in pg_cron (SELECT * FROM cron.job).
--
--   SELECT cron.schedule(
--     'scheduled-ride-digest',
--     '*/15 * * * *',
--     $$SELECT net.http_post(
--       url := 'https://hhsqwmftrrmtodvvuyxq.supabase.co/functions/v1/scheduled-ride-digest',
--       headers := '{"Content-Type":"application/json","Authorization":"Bearer <service_role_jwt>"}'::jsonb,
--       body := '{}'::jsonb
--     )$$
--   );
--
-- To verify after registering:
--   SELECT jobid, jobname, schedule FROM cron.job WHERE jobname = 'scheduled-ride-digest';
--   SELECT status, return_message, start_time FROM cron.job_run_details
--     WHERE jobid = <jobid> ORDER BY start_time DESC LIMIT 5;
--
-- Dry run before registering — safe, and the first run is safe by construction:
-- every driver's watermark starts NULL, which seeds silently and sends nothing.
-- The response reports {sent, rejected, seeded, held_by_rate_limit,
-- open_rides_in_horizon}, so the first invocation should read sent: 0 with
-- seeded equal to your tokened-driver count.
--   curl -X POST -H "Authorization: Bearer <service_role_jwt>" \
--     https://hhsqwmftrrmtodvvuyxq.supabase.co/functions/v1/scheduled-ride-digest
